"use client";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, ExternalLink } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/Badge";
import { Card, CardContent, CardHeader } from "@/components/ui/Card";
import { ErrorState, LoadingState } from "@/components/common/States";
import { api, type CertificationRequirement, type Standard, type StandardVersion } from "@/src/lib/api";
export default function StandardDetailPage(){const {id}=useParams<{id:string}>();const [data,setData]=useState<{standard:Standard;versions:StandardVersion[];amendments:Record<string,unknown>[];relationships:Record<string,unknown>[];certification:CertificationRequirement[]}|null>(null);const [error,setError]=useState("");useEffect(()=>{Promise.all([api.getStandard(id),api.getVersions(id),api.getAmendments(id),api.getRelationships(id),api.getCertification(id)]).then(([standard,versions,amendments,relationships,certification])=>setData({standard,versions,amendments,relationships,certification})).catch((e:Error)=>setError(e.message));},[id]);if(error)return <ErrorState message={error}/>;if(!data)return <LoadingState label="Loading standard"/>;const {standard}=data;return <div className="mx-auto max-w-5xl space-y-6"><Link href="/dashboard/standards" className="inline-flex items-center gap-2 text-sm text-text-muted hover:text-primary"><ArrowLeft className="h-4 w-4"/>Back to standards</Link><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-sm text-primary">{standard.standard_number}</p><h1 className="mt-2 text-2xl font-semibold">{standard.title}</h1></div><Badge>{standard.status}</Badge></div></CardHeader><CardContent className="space-y-5 p-5"><Info label="Description" value={standard.description}/><Info label="Scope" value={standard.scope}/><Info label="Technical domain" value={standard.technical_domain}/><div><p className="text-xs text-text-muted">Source</p>{standard.source_url?<a className="mt-1 inline-flex items-center gap-1 text-sm text-primary hover:underline" href={standard.source_url} target="_blank" rel="noreferrer">{standard.source_name||standard.source_url}<ExternalLink className="h-3 w-3"/></a>:<p className="mt-1 text-sm">Source not available</p>}</div></CardContent></Card><DataBlock title="Versions" rows={data.versions.map(v=>`${v.version_label||v.id}${v.is_current?" · Current version in knowledge base":""}${v.publication_date?` · ${v.publication_date}`:""}`)} /><DataBlock title="Amendments" rows={data.amendments.map(a=>JSON.stringify(a))}/><DataBlock title="Relationships" rows={data.relationships.map(r=>`${String(r.relationship_type||"related")} · ${String(r.source_standard_id||"")} → ${String(r.target_standard_id||"")}`)}/><DataBlock title="Certification requirements" rows={data.certification.map(c=>`${c.certification_name||"Certification"}${c.mandatory===true?" · Mandatory in recorded source":""}${c.description?` · ${c.description}`:""}`)}/></div>}
function Info({label,value}:{label:string;value:string|null}){return <div><p className="text-xs text-text-muted">{label}</p><p className="mt-1 text-sm leading-6">{value||"Not available in database"}</p></div>}
function DataBlock({title,rows}:{title:string;rows:string[]}){return <Card><CardHeader><h2 className="font-semibold">{title}</h2></CardHeader><CardContent>{rows.length?<ul className="space-y-2 text-sm text-text-secondary">{rows.map((r,i)=><li key={i} className="rounded-lg bg-surface-muted p-3">{r}</li>)}</ul>:<p className="text-sm text-text-muted">No records available in database.</p>}</CardContent></Card>}
