"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { Input } from "@/components/ui/Input";
import { Badge } from "@/components/ui/Badge";
import { Card, CardContent } from "@/components/ui/Card";
import { EmptyState, ErrorState, LoadingState } from "@/components/common/States";
import { api, type Standard } from "@/src/lib/api";
export default function StandardsPage(){const [q,setQ]=useState("");const [rows,setRows]=useState<Standard[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");useEffect(()=>{const timer=setTimeout(()=>{setLoading(true);api.searchStandards(q).then(setRows).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false));},250);return()=>clearTimeout(timer)},[q]);return <div className="mx-auto max-w-6xl space-y-6"><div><p className="text-sm font-medium text-primary">Knowledge base</p><h1 className="mt-1 text-3xl font-semibold">Indian Standards</h1><p className="mt-2 text-sm text-text-muted">Search source-backed standards available to the recommendation engine.</p></div><Card><CardContent className="p-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-text-muted"/><Input aria-label="Search standards" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by number, title, scope or description" className="pl-9"/></div></CardContent></Card>{error?<ErrorState message={error}/>:loading?<LoadingState label="Searching standards"/>:rows.length?<div className="grid gap-4 md:grid-cols-2">{rows.map(s=><Link key={s.id} href={`/dashboard/standards/${s.id}`}><Card className="h-full hover:border-primary/40"><CardContent className="space-y-3 p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-mono text-sm font-semibold text-primary">{s.standard_number}</h2><Badge>{s.status}</Badge></div><p className="font-medium">{s.title}</p><p className="line-clamp-3 text-sm leading-6 text-text-secondary">{s.scope||s.description||"Scope information not available."}</p><p className="text-xs text-text-muted">{s.source_name||"Source not available"}</p></CardContent></Card></Link>)}</div>:<EmptyState title={q?"No standards match this search":"No standards available in the current knowledge base"}/>}</div>}
