"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BarChart3, BookOpen, ClipboardCheck, History, Settings, ShieldCheck, Sparkles, LogOut } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { getCurrentProfile, type UserProfile } from "@/src/lib/profile";
import { signOut } from "@/src/lib/auth";

const navigation = [{label:"Dashboard",href:"/dashboard",icon:BarChart3},{label:"New Analysis",href:"/dashboard/analysis",icon:Sparkles},{label:"History",href:"/dashboard/history",icon:History},{label:"Standards",href:"/dashboard/standards",icon:BookOpen},{label:"Reviews",href:"/dashboard/reviews",icon:ClipboardCheck}];
export function Sidebar(){const pathname=usePathname();const router=useRouter();const [profile,setProfile]=useState<UserProfile|null>(null);useEffect(()=>{getCurrentProfile().then(setProfile)},[]);const active=(href:string)=>href==="/dashboard"?pathname===href:pathname.startsWith(href);const role=profile?.role?.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")||"User";async function logout(){await signOut();router.push("/login");router.refresh()}return <aside className="flex h-full flex-col"><div className="flex h-16 items-center gap-3 border-b border-border px-5"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-white"><ShieldCheck className="h-5 w-5"/></div><div><p className="text-sm font-semibold">BIS Standards</p><p className="text-xs text-text-muted">Intelligence</p></div></div><nav className="flex-1 space-y-1 px-3 py-5"><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-text-muted">Workspace</p>{navigation.map(item=><NavItem key={item.href} item={item} active={active(item.href)}/>) }{profile?.role==="admin"&&<><div className="my-5 border-t border-border"/><p className="mb-2 px-3 text-[11px] font-semibold uppercase tracking-wider text-text-muted">Administration</p><NavItem item={{label:"Admin Panel",href:"/dashboard/admin",icon:Settings}} active={active("/dashboard/admin")}/></>}</nav><div className="border-t border-border p-4"><div className="flex items-center gap-3 rounded-lg bg-surface-muted p-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-sm font-semibold text-white">{(profile?.full_name||profile?.email||"U").charAt(0).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{profile?.full_name||profile?.email||"User"}</p><p className="truncate text-xs text-text-muted">{role}</p></div><button onClick={logout} aria-label="Sign out" className="rounded-md p-2 text-text-muted hover:bg-surface hover:text-foreground"><LogOut className="h-4 w-4"/></button></div></div></aside>}
function NavItem({item,active}:{item:{label:string;href:string;icon:typeof BarChart3};active:boolean}){const Icon=item.icon;return <Link href={item.href} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${active?"bg-primary/10 text-primary":"text-text-secondary hover:bg-surface-muted hover:text-foreground"}`}><Icon className="h-[18px] w-[18px]"/><span>{item.label}</span></Link>}
